### PR TITLE
 missing target_include_directories in CMakeLists.txt

### PR DESCRIPTION
**Pull request by Xeverous**
Nana lacked exposition of public headers. Any target which links to nana (by target_link_libraries(project_name PRIVATE nana)) was failing to compile because nana did not expose public headers (#include <nana/...> were not found). 

This change adds a missing target_include_directories() command which will cause targets that link to nana to get nana's include directory.

### CODE REVIEW

**Comment by qPCR4vir** [comment]
No, this will be an error if you want to install nana. 
Please see: https://github.com/cnjinhao/nana/blob/master/build/cmake/install_nana.cmake#L21
Try to see why you have this problem.

**Comment by qPCR4vir** [comment]
please test:
https://github.com/cnjinhao/nana/pull/463

**Comment by Xeverous** [comment]
Ok, I understand. #463 is the correct way to do this. Will try and report.

**Comment by qPCR4vir** [comment]
hi, thank! This can be closed now

**Comment by Xeverous** [comment]
Tested. The build works.

**Pull request closed without merging**
