### PR TITLE
list::column_interface::fit_content should take the icon width into account

### PR DESCRIPTION
**Pull request by oltolm**

### CODE REVIEW

**Comment by qPCR4vir** [comment]
Hi,
place fit for button have the same problem.

**Comment by oltolm** [comment]
Is there a problem with this PR? Are you going to merge it?

**Comment by cnjinhao** [comment]
Thanks for fixing this issue!

**Comment by cnjinhao** [comment]
> 
> 
> Hi,
> place fit for button have the same problem.

I committed a patch to fix the problem

**Pull request merged**
