### PR TITLE
FIX 4. inputbox buttons overlaid, missed included in installed nana and both travis and appveyor IC

### PR DESCRIPTION
**Pull request by qPCR4vir**
from https://cmake.org/cmake/help/v3.0/command/target_include_directories.html

> Include directories usage requirements commonly differ between the build-tree and the install-tree. The BUILD_INTERFACE and INSTALL_INTERFACE generator expressions can be used to describe separate usage requirements based on the usage location. Relative paths are allowed within the INSTALL_INTERFACE expression and are interpreted relative to the installation prefix. For example:

```
target_include_directories(mylib PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/mylib>
  $<INSTALL_INTERFACE:include/mylib>  # <prefix>/include/mylib
)
```

### CODE REVIEW

**Comment by Xeverous** [comment]
This works, no more include errors.

You should not commit commented code though. There is already a lot of commented code in cmake files.

**Comment by qPCR4vir** [comment]
[Travis CI XVFB Breaking Change](https://benlimmer.com/2019/01/14/travis-ci-xvfb/)

**Comment by Xeverous** [comment]
Use `#define NOMINMAX` just before including `windows.h`, you may also need to add `#define WIN32_LEAN_AND_MEAN`.

**Comment by cnjinhao** [comment]
Thanks for your PR!

**Pull request merged**
