### PR TITLE
Several modifications

### PR DESCRIPTION
**Pull request by beru**
Hi, I've added several features to nana library.
- added OFN_NOCHANGEDIR flag to OPENFILENAME::Flags in nana::filebox::show
- Big & Small icon support for Windows.
  - On Windows, the system displays the large icon in the ALT+TAB dialog box, and the small icon in the window caption.
- Open icon image from memory feature.
  - nana::paint::image::open_icon method seems a bit too concrete.
  - I've added this feature to set icon image from memory that is retrieved from resource data within executable file.
- Label::relate method.
  - It works like HTML label element **for** attribute.
  - By clicking a label, specified widget will be focused.
- Textbox selection handling improvements.
  - Select textbox content after tabstop event.
  - When textbox is not focused, its selection is not drawn to make it look quiet.
  - Improved cursor move keys handling.
  - Word selection support is still missing though.

### CODE REVIEW

**Comment by beru** [comment]
On Windows, I use below code to set icon data from executable resource.

```c++
void* load_icon_res(HMODULE hModule, int id, DWORD& dwResourceSize, int cxDesired, int cyDesired)
{
	auto hResource		= FindResource(hModule, MAKEINTRESOURCE(id), RT_GROUP_ICON);	if (!hResource) { return nullptr; }
	dwResourceSize		= SizeofResource(hModule, hResource);							if (dwResourceSize == 0) { return nullptr; }
	auto hData			= LoadResource(hModule, hResource);								if (!hData) { return nullptr; }
	auto pResource		= LockResource(hData);											if (!pResource) { return nullptr; }
	id					= LookupIconIdFromDirectoryEx((LPBYTE)pResource,
													  TRUE,
													  cxDesired,
													  cyDesired,
													  LR_DEFAULTCOLOR);					if (id == 0) { return nullptr; }
	hResource			= FindResource(hModule, MAKEINTRESOURCE(id), RT_ICON);			if (!hResource) { return nullptr; }
	dwResourceSize		= SizeofResource(hModule, hResource);							if (dwResourceSize == 0) { return nullptr; }
	hData				= LoadResource(hModule, hResource);								if (!hData) { return nullptr; }
	pResource			= LockResource(hData);
	return pResource;
}

int WINAPI WinMain(
	HINSTANCE hInstance,
	HINSTANCE hPrevInstance,
	LPSTR lpCmdLine,
	int nCmdShow
	)
{
	nana::paint::image img_big_icon;
	nana::paint::image img_small_icon;
	DWORD resource_size_big = 0;
	DWORD resource_size_small = 0;
	void* res_big_icon = load_icon_res(NULL, IDI_ICON1, resource_size_big, GetSystemMetrics(SM_CXICON), GetSystemMetrics(SM_CYICON));
	void* res_small_icon = load_icon_res(NULL, IDI_ICON1, resource_size_small, GetSystemMetrics(SM_CXSMICON), GetSystemMetrics(SM_CYSMICON));
	if (res_big_icon && res_small_icon) {
		if (img_big_icon.open_icon(res_big_icon, resource_size_big)
			&& img_small_icon.open_icon(res_small_icon, resource_size_small)
		) {
			nana::API::window_icon_default(img_big_icon, img_small_icon);
		}
	}
	
	using namespace nana;

	form fm(API::make_center(500, 300));
	fm.caption(L"test");
	
	textbox txt(fm, rectangle{50, 50, 100, 30});
	txt.multi_lines(false);
	txt.caption(L"aaaa");
	
	fm.show();
	exec();

}

```

Loading icon's data from executable resource is not trivial, so it would be easier for the users if nana library could handle it.

But the problem is handling resource is dependant on operating system....

If I had to use GCC to build applications, I would use ld command to embed icon files into executable.
http://www.burtonini.com/blog/computers/ld-blobs-2007-07-13-15-50

**Comment by beru** [comment]
If I should seprate this pull request per features, I would do so.
Do you need more precise explanations of the modifications?

**Comment by cnjinhao** [comment]
Thanks for your contribution, I will study these changes and implement them for Linux

**Comment by Woolworths** [comment]
nice

**Pull request merged**
