### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by qPCR4vir**
See #107 
Please, go to https://ci.appveyor.com/login and add this project there.

### CODE REVIEW

**Comment by qPCR4vir** [comment]
TODO:
- activate clang in travis CI
- activate MacOS  in travis CI
- move demos - cmake code to the demo repo and here only include it. Include all demos, maybe "automatically".
- PNG ON: see the error here: https://travis-ci.org/qPCR4vir/nana/jobs/108676699
- Audio ON: [Could not find a package configuration file provided by "asound" ](https://travis-ci.org/qPCR4vir/nana/jobs/108672508)
- include demos in AppVeyor CI build.
- make "real" test: run the demos (not just compile) in CI and return if run OK.
- create a "framework" in Nana for automatic GUI testing !! By conditional compilation include a routine run in parallel (another thread) that will timely send both low and high level events (bottom click, mouse move, etc)

**Comment by qPCR4vir** [comment]
Hi !
Actually the demos run OK in windows, with VC2015 and with gcc++5 mingw in Clion.
It seems like there are  errors in the `std::move` implementation used in the build in travis.
See the details, from `tabbar `trying to move an `string`. I don't see any error, and the message point to an error in what `move `return

**Comment by qPCR4vir** [comment]
Urra ! Fixed !!

**Comment by cnjinhao** [comment]
I reviewed early today, and found the to_nstring issue in tabbar. But now it have been fixed by your last commit. Thank you

**Pull request merged**
