### PR TITLE
place::modify() now correctly updates the text to place::div_text.

### PR DESCRIPTION
**Pull request by dankan1890**
Note: I reverted the previous commit because it had an incorrect formatting.

### CODE REVIEW

**Comment by cnjinhao** [comment]
Thanks a lot for the patch. I have a question, why was `const` added to the setter field_display/field_visible?

**Comment by dankan1890** [comment]
Because, none of the two functions change class members, and so can also be called by const class objects.

**Comment by cnjinhao** [comment]
The question is
```c++
void foo(const place&); //it may implicitly modify a field's visibility

auto a = placeobj.div();
foo(placeobj);
auto b = placeobj.div();

if(a != b)
{
    //Should this condition be allowed?
}
```

**Comment by dankan1890** [comment]
Test code (with 2 bug reports):
```cpp
#include <nana/gui.hpp>
#include <nana/gui/widgets/label.hpp>
#include <nana/gui/widgets/button.hpp>
#include <nana/gui/widgets/listbox.hpp>
#include <nana/gui/place.hpp>
using namespace nana;

void foo(const place &obj)
{
	obj.field_visible("lbl", false);
}

int main()
{
	form fm{ API::make_center(400, 400) };
	button btn{ fm, "Select" }, inbtn{ fm, "Make label invisible"};
	label lbl{ fm, "Label is visible" }, lbldiv{ fm };
	listbox lb{ fm };
	place placeobj{ fm };

	lb.enable_single(true, false);
	auto cat = lb.append_header("TEST");
	
	for (auto x = 0; x < 100; x++)
		lb.at(cat).push_back(std::to_string(x));
	
	lb.at(cat).at(0).select(true);

	btn.events().click([&] { 
		lb.at(cat).at(50).select(true); // Note: The listbox doesn't scroll to view the selection
	});

	inbtn.events().click([&] {
		foo(placeobj);
		lbldiv.caption(placeobj.div());
	});

	placeobj.div("<vert <mydiv><lbl><inbtn>>|<vert <lb><btn>>");
	placeobj["lb"] << lb;
	placeobj["btn"] << btn;
	placeobj["inbtn"] << inbtn;
	placeobj["lbl"] << lbl;
	placeobj["mydiv"] << lbldiv; // Note: If set the field name to "lbldiv" causes a issue in the identification of "lbl" (find_idstr function)
	placeobj.collocate();
	
	lbldiv.caption(placeobj.div());

	fm.show();
	exec();
}
```

**Comment by cnjinhao** [comment]
Thanks for fixing this issue. I will make another fix for the select issue.

**Comment by cnjinhao** [comment]
BTW, it would be better that if remove the `const` for the setters field_display and field_visible.

**Comment by dankan1890** [comment]
Ok, no problem :)

**Pull request merged**
