### PR TITLE
Treebox multiselect

### PR DESCRIPTION
**Pull request by edgarbernal5**
See #691 for more details.

### CODE REVIEW

**Comment by qPCR4vir** [comment]
Well, here you will need to clean-up the PR... the last 3 commits only?

**Comment by edgarbernal5** [comment]
I can create a new branch from fresh develop branch and push the corresponding commits in a new branch.

**Comment by edgarbernal5** [comment]
Closing this PR as now we have a clean history!

**Comment by edgarbernal5** [comment]
Closing this PR as now we have a clean history!

**Pull request closed without merging**
