### PR TITLE
Added internationalization loading option with ifstream 

### PR DESCRIPTION
**Pull request by Wolowin**
Added internationalization loading option with ifstream instead of only string filename. Opens support for various usages - one of which being wstring paths on Windows.

### CODE REVIEW

**Comment by cnjinhao** [comment]
Hi, Wolowin. Thank you for your PR!
IMO, it is not recommended to overload `internationalize::open()` for `std:;ifstream`. If a file is openned in text mode, it implies that all '\r\n" are translated to "\n", then it will create a result which is different from the original file.

**Comment by Wolowin** [comment]
Hey,

I have to apologise for creating this merge request too fast - without making tripple sure that everything works. The fstream version that I suggested had some issue. I was in a rush at that day and I fell into "No need to check - it's a simple change, why wouldn't it work?" trap. Sorry for making you deal with this improfessionalmerge request. In the end I ended up using overload that accepts wstring instead of stream. I was low on time that day and wanted a solution as fast as possible. I will try to find a moment to make it work dependably for fstreams in a not-distant future.

Thank you for your time

**Comment by cnjinhao** [comment]
Never mind, we can remove the std::string version and add a std::file system::path version that can open a utf-8/local encoding/wide string file name. Please feel free to contribute to this project. I’m looking forward to your next contribution.

**Comment by Wolowin** [comment]
Hey! I have a question tho - does nana fully support utf-8 with both its internationalization class and dialogs?

**Pull request closed without merging**
