### PR TITLE
Add TravisCI support

### PR DESCRIPTION
**Pull request by nabijaczleweli**
As discussed [here](http://chat.stackoverflow.com/transcript/message/28394615#28394615).

Also adds a TravisCI build badge to the README.

How to activate:
  * Before merging the PR:
    - go to https://travis-ci.org,
    - log in (if necessary),
    - click your name and avatar in the top-right corner,
    - check (click on, so it turns from grey to green) `cnjinhao/nana`,
    - click on the little gear icon, which will take you to the settings page,
    - check the option in the top-left corner ("Build only if .travis.yml is present").
  * Merge the PR.

Now, each time a commit is pushed to a branch containing a `.travis.yml` file, a build will start and, if it fails, responsible individuals will be notified via e-mail.
Also, if a PR is opened (and is auto-mergable), a build will start targeting the merged state.

### CODE REVIEW

**Comment by qPCR4vir** [comment]
Hi!
Thank !!
@cnjinhao I have merged all of this and it runs travis.
This are my first results (sadly negative, but I think you know why):

`1.28s$ cmake -G"Unix Makefiles" .. -DENABLE_JPEG=ON -DENABLE_PNG=ON

-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.4.8") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.46") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/build/qPCR4vir/nana/bld
The command "cmake -G"Unix Makefiles" .. -DENABLE_JPEG=ON -DENABLE_PNG=ON" exited with 0.
9.44s$ make
Scanning dependencies of target nana
[  1%] Building CXX object CMakeFiles/nana.dir/source/any.cpp.o
[  2%] Building CXX object CMakeFiles/nana.dir/source/basic_types.cpp.o
[  3%] Building CXX object CMakeFiles/nana.dir/source/charset.cpp.o
[  5%] Building CXX object CMakeFiles/nana.dir/source/datetime.cpp.o
[  6%] Building CXX object CMakeFiles/nana.dir/source/deploy.cpp.o
[  7%] Building CXX object CMakeFiles/nana.dir/source/internationalization.cpp.o
[  8%] Building CXX object CMakeFiles/nana.dir/source/unicode_bidi.cpp.o
[ 10%] Building CXX object CMakeFiles/nana.dir/source/detail/platform_spec_posix.cpp.o
[ 11%] Building CXX object CMakeFiles/nana.dir/source/detail/platform_spec_windows.cpp.o
[ 12%] Building CXX object CMakeFiles/nana.dir/source/filesystem/filesystem.cpp.o
[ 13%] Building CXX object CMakeFiles/nana.dir/source/audio/player.cpp.o
In file included from /home/travis/build/qPCR4vir/nana/source/audio/player.cpp:3:0:
/home/travis/build/qPCR4vir/nana/include/nana/audio/detail/audio_device.hpp:10:30: fatal error: alsa/asoundlib.h: No such file or directory
compilation terminated.`

**Comment by qPCR4vir** [comment]
upps, with clang another problem:

1.13s$ cmake -G"Unix Makefiles" .. -DENABLE_JPEG=ON -DENABLE_PNG=ON
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/clang-3.8
-- Check for working C compiler: /usr/bin/clang-3.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-3.8
-- Check for working CXX compiler: /usr/bin/clang++-3.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.4.8") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.46") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/travis/build/qPCR4vir/nana/bld
The command "cmake -G"Unix Makefiles" .. -DENABLE_JPEG=ON -DENABLE_PNG=ON" exited with 0.
0.14s$ make
Scanning dependencies of target nana
[  1%] Building CXX object CMakeFiles/nana.dir/source/any.cpp.o
In file included from /home/travis/build/qPCR4vir/nana/source/any.cpp:16:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/utility:70:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:59:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/move.h:168:14: error: 
      missing 'typename' prior to dependent type name
      '__and_<is_nothrow_move_constructible<_Tp>,
      is_nothrow_move_assignable<_Tp> >::value'
    noexcept(__and_<is_nothrow_move_constructible<_Tp>,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/move.h:166:9: error: 
      function cannot return function type 'void
      (__and_<is_nothrow_move_constructible<_Tp>,
      is_nothrow_move_assignable<_Tp> >::value)'
    swap(_Tp& __a, _Tp& __b)
        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/move.h:185:5: error: 
      illegal initializer (only variables can be initialized)
    swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/move.h:187:41: error: 
      expected ';' at end of declaration
    noexcept(noexcept(swap(*__a, *__b)))
                                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/move.h:189:5: error: 
      expected unqualified-id
    {
    ^
In file included from /home/travis/build/qPCR4vir/nana/source/any.cpp:16:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/utility:70:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:167:16: error: 
      missing 'typename' prior to dependent type name
      '__and_<is_nothrow_move_assignable<_T1>, is_nothrow_move_assignable<_T2>
      >::value'
      noexcept(__and_<is_nothrow_move_assignable<_T1>,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:166:16: error: 
      function cannot return function type 'pair<_T1, _T2>
      &(__and_<is_nothrow_move_assignable<_T1>, is_nothrow_move_assignable<_T2>
      >::value)'
      operator=(pair&& __p)
               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:30: error: 
      C++ requires a type specifier for all declarations
      noexcept(noexcept(swap(first, __p.first))
                             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:37: error: 
      unknown type name '__p'
      noexcept(noexcept(swap(first, __p.first))
                                    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:40: error: 
      expected ')'
      noexcept(noexcept(swap(first, __p.first))
                                       ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:29: note: 
      to match this '('
      noexcept(noexcept(swap(first, __p.first))
                            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:25: error: 
      C++ requires a type specifier for all declarations
      noexcept(noexcept(swap(first, __p.first))
                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:196:9: error: 
      expected ')'
               && noexcept(swap(second, __p.second)))
               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:195:15: note: 
      to match this '('
      noexcept(noexcept(swap(first, __p.first))
              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:194:11: error: 
      function cannot return function type 'void (int ((*)(int, int)))'
      swap(pair& __p)
          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:255:23: error: 
      use of undeclared identifier '__x'
    noexcept(noexcept(__x.swap(__y)))
                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:255:32: error: 
      use of undeclared identifier '__y'
    noexcept(noexcept(__x.swap(__y)))
                               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:255:38: error: 
      expected ';' at end of declaration
    noexcept(noexcept(__x.swap(__y)))
                                     ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:256:5: error: 
      expected unqualified-id
    { __x.swap(__y); }
    ^
/home/travis/build/qPCR4vir/nana/source/any.cpp:73:3: error: no matching
      function for call to 'swap'
                std::swap(content_, other.content_);
                ^~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/stl_pair.h:254:5: note: 
      candidate template ignored: could not match 'pair<type-parameter-0-0,
      type-parameter-0-1>' against 'nana::any::content_interface *'
    swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
    ^
18 errors generated.
make[2]: *** [CMakeFiles/nana.dir/source/any.cpp.o] Error 1
make[1]: *** [CMakeFiles/nana.dir/all] Error 2
make: *** [all] Error 2
The command "make" exited with 2.
cache.2
store build cache
0.00s
2.53schanges detected, packing new archive
uploading archive
Done. Your build exited with 1.

**Comment by nabijaczleweli** [comment]
Ready for merge, current branch compiles fine (well, it will, after #106 gets merged)/

**Comment by qPCR4vir** [comment]
This was OK (do you see it?)
https://travis-ci.org/qPCR4vir/nana/jobs/105405837

but the last fail again.
https://travis-ci.org/qPCR4vir/nana/jobs/105412110

**Comment by nabijaczleweli** [comment]
@qPCR4vir I rebased and force-pushed my branch. See [build status for my fork](https://travis-ci.org/nabijaczleweli/nana/builds/105411911), which fails in a way, that's fixed by #106.

**Comment by qPCR4vir** [comment]
I see... you need to pick your own:   :-)
8ea8322fc3a198e25ee3dd88e472a40cb1ab4f60
back

It is Ok now:
https://github.com/qPCR4vir/nana/tree/gcc_travis
https://travis-ci.org/nabijaczleweli/nana/jobs/105411912

**Comment by qPCR4vir** [comment]
@nabijaczleweli 
Thank you !
We will build upon this and will try to fix all the problems with clang and PNG,
but it will be great if you keep helping us ... and better if you try (and enjoy) nana...
We have a lot to do to improve nana... but I'm very happy using it in my PhD thesis - it already works.

**Comment by qPCR4vir** [comment]
ufff... I cannot make travis build with clang...

**Comment by nabijaczleweli** [comment]
That's standard library code you're failing on, and there's not much (well, except for installing `libc++`) you can do.

**Comment by qPCR4vir** [comment]
Hi !
I dint solve the problems with clang... it is under `allow_failures:` and actually not building now. Waiting for a solution - it will be very good to have CI with clang, for better error messages, etc.
It is working with gcc on Linux. 
Nana compile OK.
But the examples not: see: https://travis-ci.org/qPCR4vir/nana/jobs/108552005
It seems that each reference to X11 functions is undefined.
Do you know why?

I added Windows CI: see: https://github.com/qPCR4vir/nana
(I will make a PR but I need to do some cleanup first, you can merge - cherrypick - directly if you have the time of course)

[ 82%] Building CXX object CMakeFiles/nana.dir/source/threads/pool.cpp.o
[ 83%] Linking CXX static library libnana.a
[ 83%] Built target nana
Scanning dependencies of target a_group_impl
[ 84%] Building CXX object CMakeFiles/a_group_impl.dir/nana-demo/Examples/a_group_impl.cpp.o
[ 85%] Linking CXX executable a_group_impl
libnana.a(bedrock_posix.cpp.o): In function `nana::detail::window_proc_for_xevent(_XDisplay*, _XEvent&)':
bedrock_posix.cpp:(.text+0x2e2d): undefined reference to `Xutf8LookupString'
bedrock_posix.cpp:(.text+0x2e8f): undefined reference to `Xutf8LookupString'
bedrock_posix.cpp:(.text+0x2ed3): undefined reference to `XLookupKeysym'
bedrock_posix.cpp:(.text+0x3744): undefined reference to `XLookupKeysym'
libnana.a(bedrock_posix.cpp.o): In function `nana::detail::bedrock::set_cursor(nana::detail::basic_window*, nana::cursor, nana::detail::bedrock::thread_context*)':
bedrock_posix.cpp:(.text+0x4249): undefined reference to `XUndefineCursor'
bedrock_posix.cpp:(.text+0x4296): undefined reference to `XFreeCursor'
bedrock_posix.cpp:(.text+0x42dd): undefined reference to `XUndefineCursor'
bedrock_posix.cpp:(.text+0x42fd): undefined reference to `XCreateFontCursor'
bedrock_posix.cpp:(.text+0x432d): undefined reference to `XDefineCursor'
libnana.a(native_window_interface.cpp.o): In function `nana::detail::native_interface::primary_monitor_size()':
native_window_interface.cpp:(.text+0x28): undefined reference to `XDefaultScreen'
native_window_interface.cpp:(.text+0x43): undefined reference to `XScreenOfDisplay'
native_window_interface.cpp:(.text+0x53): undefined reference to `XHeightOfScreen'
native_window_interface.cpp:(.text+0x61): undefined reference to `XWidthOfScreen'

**Comment by nabijaczleweli** [comment]
Re: X11 functions; I managed to cut down the linker errors all the way down to `pthread`, which I failed at resolving, on my fork.

**Comment by qPCR4vir** [comment]
Hi !!
It is working: https://github.com/qPCR4vir/nana
The Linux build include 4 demos !

Of course, there is a lot to do... but it is a serious step for me (je - that was my first executable compiled in Linux). I need to do a lot of cleanup.

Thank you !

**Comment by qPCR4vir** [comment]
Wonderfull !
Now I have a [todo list](https://github.com/cnjinhao/nana/pull/109#issuecomment-183312674).

**Pull request merged**
