### PR TITLE
3 instead of 1 step by list wheel scroll

### PR DESCRIPTION
**Pull request by qPCR4vir**
A very simple but effective improvement

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
This should actually be read from OS settings, not hardcoded

**Comment by cnjinhao** [comment]
Scheme is better, how about the default scheme value to be initialized with OS setting? as mentioned by @nabijaczleweli

**Comment by qPCR4vir** [comment]
Hi,
yes... 

>  the default scheme value to be initialized with OS setting?

is perfect... only I dont know how.. I hope you know :-) 
I think is is best to move as much as possible to the scheme. 

It open the possibilities to adapt all (different forms factors, etc. ... for the future)

**Comment by Pr0curo** [comment]
for windows you can use SystemParametersInfo with SPI_GETWHEELSCROLLLINES

i dont know about the linux/mac way :/

**Comment by cnjinhao** [comment]
@qPCR4vir I will merge the changes.
@Pr0curo Thanks for the informations, I will hardcode for linux/mac.

**Comment by nabijaczleweli** [comment]
It's probably acessible via some API for Mac as well

**Pull request merged**
