### PR TITLE
fix crash by using empty path to initialize folderbox with fs canonical() which don't exist

### PR DESCRIPTION
**Pull request by qPCR4vir**
After debugging, it resolved my problem in: https://github.com/cnjinhao/nana/issues/408

### CODE REVIEW

**Comment by qPCR4vir** [comment]
well, it seems that not many implementations of filesystem implement `weakly_canonical`. 
It may be better to catch the exception in `canonical` in `folderbox `?

**Comment by cnjinhao** [comment]
Thanks for your PR!

**Comment by qPCR4vir** [comment]
thank!
I updated my MS project to use the latest c++ standard and now I have `weakly_canonical`. 
Compiling OK with MinGW-gcc8.3 and MSVS2017

**Comment by dudztroyer** [comment]
My VS2017 refuses to compile with ``weakly_canonical``
https://upload.wsbot.net/files/devenv_2019-04-08_01-44-32.png
``Not a member of std::filesystem`` and ``identifier not found`` are the translation for the errors.

**Comment by qPCR4vir** [comment]
No problems, just read this:
https://stackoverflow.com/questions/50668814/vs2017-e0135-namespace-std-has-no-member-filesystem
Ask back if still have problems

**Pull request merged**
